version: '3.8'

services:
  mongodb:
    image: mongo:latest
    hostname: cluster0.xxxxx.mongodb.net
    container_name: mongodb_service
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user1
      MONGO_INITDB_ROOT_PASSWORD: pwduser1
    networks:
      - local_net

  java_app:
    image: eclipse-temurin:latest
    container_name: java_app_container
    command: sleep 1d
    working_dir: /app
    volumes:
      - ./drivers/java-sync:/app
    networks:
      - local_net

networks:
  local_net:
    driver: bridge

volumes:
  mongo_data:
    driver: local